steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${_VAPID_PUBLIC_KEY}"
      - "--build-arg"
      - "COMMIT_SHA=$COMMIT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nom:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nom:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "nom"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nom:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--set-env-vars"
      - "FIREBASE_ADMIN_PROJECT_ID=$PROJECT_ID,ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY},NEXT_PUBLIC_VAPID_PUBLIC_KEY=${_VAPID_PUBLIC_KEY},VAPID_PRIVATE_KEY=${_VAPID_PRIVATE_KEY},VAPID_SUBJECT=mailto:nom@paulchun.com"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "2"

substitutions:
  _FIREBASE_API_KEY: "AIzaSyC2u4nkuyMhLQpySHkKtOSdiAD6Hgy6HS8"
  _FIREBASE_AUTH_DOMAIN: "fattytoro.firebaseapp.com"
  _FIREBASE_STORAGE_BUCKET: "fattytoro.firebasestorage.app"
  _FIREBASE_MESSAGING_SENDER_ID: "1060643788581"
  _FIREBASE_APP_ID: "1:1060643788581:web:99796fff77d78f2d482ccc"
  _VAPID_PUBLIC_KEY: "BMhL71BYZlrf0W9MldkzSbE7ZXfS_9s6Q00nr__1nmFAb-l2WIdEvnkV-MSCZm5wqN5zG8X4qaOx50a-a8Ge4_k"
  _VAPID_PRIVATE_KEY: "9i7sKMUQQBxWOFanVFVHAF5MLPGm2gbXuXeaCcaqAj4"
  _ANTHROPIC_API_KEY: ""

options:
  logging: CLOUD_LOGGING_ONLY
